GCMS:
  - CNRM-CM5
  - GFDL-CM3
SCENARIOS:
  - hist
  - rcp45
  - rcp85
DOWNSCALING_METHODS:
  - bcsd
  - loca
  - icar
DISAGG_METHODS:
  - metsim
HYDRO_METHODS:
  vic_mpr: vic
  vic_default: vic
  prms_default: prms
ROUTING_METHODS:
  - mizuroute
SCEN_YEARS:
  hist:
    start: 2000
    stop: 2005
  rcp45:
    start: 2006
    stop: 2010
  rcp85:
    start: 2006
    stop: 2010
  obs_hist:
    start: 2000
    stop: 2005
DISAGG_CHUNKS:
  lat: 1
  lon: 464

machine: cheyenne_dav
workdir: /gpfs/flash/jhamman/storylines_test_full/
__default__:
  submit_cmd: qsub -j oe
  account: -A P48500028
  queue: -q share
  walltime: -l walltime=00:30:00
  resources: -l select=1
downscaling:
  submit_cmd: sbatch --export=LD_LIBRARY_PATH=
  queue: -C skylake
  walltime: -t 30:00
  resources: -n 1 --cpus-per-task=4 --mem=75G
run_metsim:
  queue: -q economy
  walltime: -l walltime=2:00:00
  resources: -l select=1:ncpus=36:mpiprocs=36:ompthreads=1
run_metsim_rcp:
  queue: -q economy
  walltime: -l walltime=4:00:00
  resources: -l select=1:ncpus=36:mpiprocs=36:ompthreads=1
run_vic:
  queue: -q economy
  walltime: -l walltime=12:00:00
  resources: -l select=1:ncpus=36:mpiprocs=36:ompthreads=1

domain: /glade/p/ral/hap/jhamman/inputdata/domains/domain.vic.conus0.0125deg_newman.20180326.nc

# Configuration settings for each method
DISAGG:
  metsim:
    executable: /glade/u/home/jhamman/miniconda3/envs/chains/bin/ms
    template: /glade/u/home/jhamman/projects/storylines/storylines_workflow/templates/metsim.template.cfg
    1440:
      out_vars:
        - t_min
        - t_max
        - prec
        - vapor_pressure
        - shortwave
        - tskc
        - pet
    60:
      out_vars:
        - temp
        - prec
        - shortwave
        - longwave
        - vapor_pressure
        - wind
        - air_pressure

# A 'model' is the combination of an executable, parameters, and config options
HYDROLOGY:
  vic_mpr:
    prerun_cmd: "module load ncarcompilers/0.4.1 intel/19.0.2 impi/2019.2.187 netcdf/4.6.1 && OMP_NUM_THREADS=1"
    executable: /glade/work/jhamman/storylines/src/VIC/vic/drivers/image/vic_image.exe
    parameters: /glade/work/jhamman/storylines/data/vic_params/mpr_0.125deg.vic_parameters.qc.nc
    template: /glade/u/home/jhamman/projects/storylines/storylines_workflow/templates/vic.template.cfg
    force_timestep: 60
    baseflow: NIJSSEN2001
  vic_default:
    prerun_cmd: "module load ncarcompilers/0.4.1 intel/19.0.2 impi/2019.2.187 netcdf/4.6.1 && OMP_NUM_THREADS=1"
    executable: /glade/work/jhamman/storylines/src/VIC/vic/drivers/image/vic_image.exe
    parameters: /glade/work/jhamman/storylines/data/vic_params/maurer_0.125deg.vic_parameters.qc.nc
    template: /glade/u/home/jhamman/projects/storylines/storylines_workflow/templates/vic.template.cfg
    force_timestep: 60
    baseflow: ARNO
  prms_default:
    executable: /glade/work/jhamman/storylines/src/PRMS_V/bin/prmsv
    parameters: /glade/p/ral/hap/mizukami/storylines/prms/scripts/preprocess/project/nldas_prms_conus12k.wpar
    template: /glade/u/home/jhamman/projects/storylines/storylines_workflow/templates/prms.template.cfg
    data_file: /glade/u/home/jhamman/projects/storylines/storylines_workflow/templates/prms_data_file.txt
    grid_file: /glade/p/ral/hap/mizukami/storylines/prms/project/nldas_prms_conus12k_hruid.txt
    force_timestep: 1440

OBS_FORCING:
  livneh:
    data: /glade/p/ral/hap/common_data/Livneh_met/livneh2014.1_16deg/8th/livneh_NAmerExt_15Oct2014.*.nc
    variables:
      lat: lat
      lon: lon
      prec: Prec
      t_max: Tmax
      t_min: Tmin
      wind: wind
  gmet_v1:
    data: /gpfs/fs1/scratch/jhamman/GARD_inputs/gmet_ensemble/conus_ens_002.nc
    variables:
      lat: lat
      lon: lon
      prec: pcp
      t_max: t_max
      t_min: t_min
  gmet_v2:
    data: /glade/p/ral/hap/anewman/conus_v1p2/eighth/v2_landmask/conus_daily_eighth_*_002.nc4
    variables:
      lat: lat
      lon: lon
      prec: pcp
      t_max: t_max
      t_min: t_min

DOWNSCALING:
  icar:
    data: /glade/p/ral/hap/trude/conus_icar/qm_data/{gcm}_{scen}_exl_conv.nc
    gcms:  # Mapping from dataset notation to official CMIP5 notation
      cnrm: CNRM-CM5
      gfdl: GFDL-CM3
    variables:
      lat: lat
      lon: lon
      prec: pcp
      t_max: t_max
      t_min: t_min
  bcsd:
    data: /glade/p/ral/hap/common_data/BCSD/BCSD_daily_forc_nc/{gcm}_{scen}_*/conus_c5.{gcm}_{scen}_*.daily.*.nc
    gcms:  # Mapping from dataset notation to official CMIP5 notation
      cnrm-cm5: CNRM-CM5
      gfdl-cm3: GFDL-CM3
    variables:
      lat: latitude
      lon: longitude
      prec: pr
      t_max: tasmax
      t_min: tasmin
      wind: wind
  loca:
    data: /glade/p/ral/hap/common_data/LOCA/met/{gcm}/8th/{scen}/*/*/*_day_{gcm}_{scen}_*.LOCA_2016-04-02.8th.nc
    gcms:  # Mapping from dataset notation to official CMIP5 notation
      CNRM-CM5: CNRM-CM5
      GFDL-CM3: GFDL-CM3
    variables:
      lat: lat
      lon: lon
      prec: pr
      t_max: tasmax
      t_min: tasmin
