name: chains
channels:
  - conda-forge
dependencies:
  # Basics
  - python=3.6
  - pip
  - jupyter
  - jupyterlab
  # Computation
  - pandas
  - xarray
  - numpy
  - scipy
  - dask
  - distributed
  - numba
  - bottleneck
  - toolz
  - scikit-learn
  - geopandas
  # I/O
  - netcdf4
  - h5netcdf
  - rasterio
  - h5py
  - cdo
  - configobj
  # Plotting and visualization
  - matplotlib
  - seaborn
  - cartopy
  - seaborn
  # Testing
  - pytest
  - flake8
  - ipython
  - jupyterlab
  - metsim=>2.0.1
  - bioconda::snakemake
  - pip:
    - git+https://github.com/UW-Hydro/tonic.git
    - git+https://github.com/jhamman/storylines.git
